# Rubocop is wrong about these styles.
Style/EmptyMethod:
  Enabled: False
Style/RaiseArgs:
  EnforcedStyle: compact
Style/MultilineIfModifier:
  Enabled: False
Documentation:
  Enabled: False
Style/FrozenStringLiteralComment:
  Enabled: False
Style/UnneededInterpolation:
  Enabled: False
# Rubocop is maybe right here but I need to exclude
# These particular files
Metrics/LineLength:
  Exclude:
    - db/**/*.rb
    - spec/**/*.rb
    - config/**/*.rb
    - app/controllers/rehearsals_controller.rb
Metrics/MethodLength:
  Exclude:
    - db/**/*.rb
    - app/models/ability.rb
    - app/controllers/rehearsals_controller.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/**/*.rb
Metrics/AbcSize:
  Exclude:
    - app/models/ability.rb

AllCops:
  Exclude:
    # I didn't write Devise. I'm not going to fix it
    # for Rubocop.
    - app/controllers/my_devise/*.rb
    # The CircleCI build when creating the Schema has
    # all kinds of troubles because the Rails migrations
    # don't apparently generate exactly according to
    # Rubocop's rules.
    - db/schema.rb
    # The Rails team's Active Storage auto-migrations that 
    # cause a large number of Rubocop errors. I'm not 
    # going to mess with or second-guess their changes.
    - db/migrate/*active_storage.rb
